### ISSUE TITLE
Markbot tell me I should not change the code.

### ISSUE THREAD

**Issue by NiallBoyd** [NiallBoyd/retina-gallery#1]
@charlie-quinn Markbot tell me I should not change the code.

**Comment by charlie-quinn** [comment]
- [ ] I can see that your `index.html` has been changed – download the assignment again and replace your code files with the new ones
- [ ] Compress and resize all images according to the assignment's guidelines

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
